INSERT INTO public.product ("name", url, value) VALUES ('Hydrating Face Cream','https://placehold.co/600x400', 29.99);
INSERT INTO public.product ("name", url, value) VALUES ('Revitalizing Eye Serum','https://placehold.co/600x400', 49.99);
INSERT INTO public.product ("name", url, value) VALUES ('Anti-Aging Night Cream','https://placehold.co/600x400', 39.99);
INSERT INTO public.product ("name", url, value) VALUES ('Vitamin C Brightening Serum','https://placehold.co/600x400', 35.50);
INSERT INTO public.product ("name", url, value) VALUES ('Aloe Vera Moisturizer','https://placehold.co/600x400', 25.00);
INSERT INTO public.product ("name", url, value) VALUES ('Charcoal Face Mask','https://placehold.co/600x400', 19.99);
INSERT INTO public.product ("name", url, value) VALUES ('Exfoliating Scrub','https://placehold.co/600x400', 17.50);
INSERT INTO public.product ("name", url, value) VALUES ('Soothing Toner','https://placehold.co/600x400', 22.99);
INSERT INTO public.product ("name", url, value) VALUES ('Hyaluronic Acid Serum','https://placehold.co/600x400', 44.00);
INSERT INTO public.product ("name", url, value) VALUES ('SPF 50 Sunscreen','https://placehold.co/600x400', 24.99);
INSERT INTO public.product ("name", url, value) VALUES ('Lip Balm','https://placehold.co/600x400', 9.99);
INSERT INTO public.product ("name", url, value) VALUES ('Cleansing Oil','https://placehold.co/600x400', 27.50);
INSERT INTO public.product ("name", url, value) VALUES ('Detoxifying Clay Mask','https://placehold.co/600x400', 20.00);
INSERT INTO public.product ("name", url, value) VALUES ('Nourishing Hair Oil','https://placehold.co/600x400', 18.75);
INSERT INTO public.product ("name", url, value) VALUES ('Whitening Toothpaste','https://placehold.co/600x400', 8.99);
INSERT INTO public.product ("name", url, value) VALUES ('Hand Cream','https://placehold.co/600x400', 15.50);
INSERT INTO public.product ("name", url, value) VALUES ('Foot Scrub','https://placehold.co/600x400', 12.99);
INSERT INTO public.product ("name", url, value) VALUES ('Eye Makeup Remover','https://placehold.co/600x400', 14.99);
INSERT INTO public.product ("name", url, value) VALUES ('Body Lotion','https://placehold.co/600x400', 19.99);
INSERT INTO public.product ("name", url, value) VALUES ('Facial Cleanser','https://placehold.co/600x400', 23.50);
INSERT INTO public.product ("name", url, value) VALUES ('Hair Conditioner','https://placehold.co/600x400', 13.99);
INSERT INTO public.product ("name", url, value) VALUES ('Shampoo','https://placehold.co/600x400', 12.50);
INSERT INTO public.product ("name", url, value) VALUES ('Facial Mist','https://placehold.co/600x400', 16.99);
INSERT INTO public.product ("name", url, value) VALUES ('Aftershave Balm','https://placehold.co/600x400', 21.50);
INSERT INTO public.product ("name", url, value) VALUES ('Cuticle Oil','https://placehold.co/600x400', 11.50);
INSERT INTO public.product ("name", url, value) VALUES ('Foot Cream','https://placehold.co/600x400', 10.99);
INSERT INTO public.product ("name", url, value) VALUES ('Face Scrub','https://placehold.co/600x400', 14.99);
INSERT INTO public.product ("name", url, value) VALUES ('Beard Oil','https://placehold.co/600x400', 18.00);
INSERT INTO public.product ("name", url, value) VALUES ('Hair Mask','https://placehold.co/600x400', 20.00);
INSERT INTO public.product ("name", url, value) VALUES ('Deodorant','https://placehold.co/600x400', 7.99);
INSERT INTO public.product ("name", url, value) VALUES ('Lip Scrub','https://placehold.co/600x400', 6.50);
INSERT INTO public.product ("name", url, value) VALUES ('Body Scrub','https://placehold.co/600x400', 19.50);
INSERT INTO public.product ("name", url, value) VALUES ('Nail Polish Remover','https://placehold.co/600x400', 5.99);
INSERT INTO public.product ("name", url, value) VALUES ('Face Oil','https://placehold.co/600x400', 24.99);
INSERT INTO public.product ("name", url, value) VALUES ('Face Mask','https://placehold.co/600x400', 9.99);
INSERT INTO public.product ("name", url, value) VALUES ('Body Oil','https://placehold.co/600x400', 22.50);
INSERT INTO public.product ("name", url, value) VALUES ('BB Cream','https://placehold.co/600x400', 30.00);
INSERT INTO public.product ("name", url, value) VALUES ('CC Cream','https://placehold.co/600x400', 32.00);
INSERT INTO public.product ("name", url, value) VALUES ('Hair Serum','https://placehold.co/600x400', 27.50);
INSERT INTO public.product ("name", url, value) VALUES ('Makeup Primer','https://placehold.co/600x400', 18.99);
INSERT INTO public.product ("name", url, value) VALUES ('Face Primer','https://placehold.co/600x400', 16.50);
INSERT INTO public.product ("name", url, value) VALUES ('Body Wash','https://placehold.co/600x400', 11.99);
INSERT INTO public.product ("name", url, value) VALUES ('Hair Gel','https://placehold.co/600x400', 14.00);
INSERT INTO public.product ("name", url, value) VALUES ('Hairspray','https://placehold.co/600x400', 13.50);
INSERT INTO public.product ("name", url, value) VALUES ('Setting Spray','https://placehold.co/600x400', 15.00);
INSERT INTO public.product ("name", url, value) VALUES ('Eyelash Serum','https://placehold.co/600x400', 28.00);
INSERT INTO public.product ("name", url, value) VALUES ('Brow Gel','https://placehold.co/600x400', 12.50);
INSERT INTO public.product ("name", url, value) VALUES ('Self-Tanning Lotion','https://placehold.co/600x400', 22.00);
INSERT INTO public.product ("name", url, value) VALUES ('Nail Strengthener','https://placehold.co/600x400', 8.75);
INSERT INTO public.product ("name", url, value) VALUES ('Eye Cream','https://placehold.co/600x400', 26.50);